### ISSUE TITLE
I cannot start Depressurizer

### ISSUE THREAD

**Issue by DARKKi** [Depressurizer/Depressurizer#129]
I am using the newest version (0.7.3) with Windows 10

When i try to start it i get this:

Error Type: TargetInvocationException
Error Message: Exception has been thrown by the target of an invocation.
Stack Trace:

TargetInvocationException: Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName)
   at Depressurizer.FormMain.InitializeComponent()
   at Depressurizer.FormMain..ctor()
   at Depressurizer.Program.Main(String[] args)

**Comment by Theo47** [comment]
Can you try this version and check if it gives you a more detailed error message?

[depressurizer.zip](https://github.com/Depressurizer/Depressurizer/files/1241295/depressurizer.zip)

**Comment by bloodythorn** [comment]
I know this issue is old, however I am having a similar issue with 0.7.4.1.

I tried the zip above, and I get the same error:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Roboto' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font.Initialize(String familyName, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName)
   at Depressurizer.FormMain.InitializeComponent() in D:\Theo\Desktop\depressurizer\src\Depressurizer\MainForm.Designer.cs:line 223
   at Depressurizer.FormMain..ctor() in D:\Theo\Desktop\depressurizer\src\Depressurizer\MainForm.cs:line 142
   at Depressurizer.Program.Main(String[] args) in D:\Theo\Desktop\depressurizer\src\Depressurizer\Program.cs:line 65

**Comment by Theo47** [comment]
Can you try these two things (in this order):
a) Download this version of depressurizer and run it: [depressurizer.zip](https://github.com/Depressurizer/Depressurizer/files/1309362/depressurizer.zip)
b) Install this font then run the [latest version](https://github.com/Depressurizer/Depressurizer/releases/tag/v0.7.4.1) of depressurizer. [Roboto-Regular.zip](https://github.com/Depressurizer/Depressurizer/files/1309361/Roboto-Regular.zip)

In both cases, if it gives an error, pay attention if the error is still `Font 'Roboto' does not support style 'Regular'`

**Comment by bloodythorn** [comment]
>> Can you try these two things (in this order):
>> a) Download this version of depressurizer and run it: depressurizer.zip

  Ran just fine.

>> b) Install this font then run the latest version of depressurizer. Roboto-Regular.zip

  Font installed no problem.
  Latest Version ran just fine.

  Can no longer re-produce the error.

**Comment by Theo47** [comment]
Nice. Thanks for the info.

Fixed. 9a91d05f9533ad479d083139048dd5611771ab3c
