### ISSUE TITLE
Counter Strike Condition Zero Deleted Scenes (Appid: 100) dosen't show

### ISSUE THREAD

**Issue by StarWeaver** [Depressurizer/Depressurizer#133]
This one won't show up in depressurizer even after I add it to a category in steam itself and reimport the steam configuration. (That fixed a missing "7,62 Hard Life")

Might have something to do with it being such an early valve title?

**Comment by Theo47** [comment]
I think this is caused because it doesn't have its own steam store page. Depressurizer can't tell if it is an actual game or just a dlc so it filters it out by default.

Easiest way to fix this would be to go to Tools->Database Editor, find the game and edit its type from Unknown to Game.

**Comment by mvegter** [comment]
@StarWeaver I have a fix for this, but it is not yet public.

**Comment by richardfrost** [comment]
I came across this issue as well, and a few others:

- **100** Counter-Strike: Condition Zero Deleted Scenes
- **32140** Midnight Mysteries: The Edgar Allan Poe Conspiracy (Renamed to "Midnight Mysteries" in the store?)
- **40970** Stronghold Crusader Extreme HD
- **495280** Disgaea 2 PC Demo
- **108200** Ticket to Ride
- **271900** Hexcells Plus
- **259080** Just Cause 2: Multiplayer Mod
- **367580** Hook

With the information you gave above, I was able to get CS: Condition Zero Deleted Scenes to work, but 
in the case of "Ticket to Ride" it is already marked as a game, so I'm not sure what to do to make it show up. When I turn on verbose logging and "Update Game List" I see this relevant message:

```VERB: Skipped integrating game: 108200 - Ticket to Ride.```

How do I make it not skip that game?

I do see this error every time I start depressurizer, are they perhaps related?

```Error updating from local files: The given key was not present in the dictionary.```

And in the logs when I run the "Update Game List" manually:

```
ERR: Exception when performing local update.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps) in D:\Theo\Desktop\depressurizer\src\Depressurizer\GameData.cs:line 1017
   at Depressurizer.FormMain.UpdateLibrary() in D:\Theo\Desktop\depressurizer\src\Depressurizer\MainForm.cs:line 903
```

If there is a way for me to give you more info, just let me know. Thanks for maintaining such an awesome project. I would cry having to manage my steam library with the steam client.
