### ISSUE TITLE
[BUG] Crash on removing multiple autocats from a group autocat

### ISSUE THREAD

**Issue by GoalieGuy6** [Depressurizer/Depressurizer#136]
**Describe the bug**
The application crashes when attempting to remove multiple autocats from a group autocat.

```
System.InvalidOperationException: List that this enumerator is bound to has been modified. An enumerator can only be used if the list does not change.
   at System.Windows.Forms.ListBox.ItemArray.EntryEnumerator.System.Collections.IEnumerator.MoveNext()
   at Depressurizer.AutoCats.AutoCatConfigPanel_Group.btnRemove_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**

1. Create a group of autocats in the edit autocat interface
2. Select multiple autocats via shift/ctrl click and click remove autocat.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Depressurizer Version 4.9.0.0
 -  .NET Version 4.7.2

**Comment by mvegter** [comment]
Hi @GoalieGuy6 , thanks for your report. I'm not able to reproduce this as using CTRL / SHIFT is not possible in the AutoCats interface.

**Comment by GoalieGuy6** [comment]
It occurs under the "Group Autocat" form specifically and I've reproduced it in v5.1.1.0 - perhaps I wasn't descriptive enough.

https://user-images.githubusercontent.com/826614/125241648-b6e1a380-e2b9-11eb-90b8-109276af73c1.mp4

**Comment by mvegter** [comment]
Hi @GoalieGuy6 , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
