### ISSUE TITLE
[BUG] NRE crash at first time launch adding new profile

### ISSUE THREAD

**Issue by SpaceArchMage** [Depressurizer/Depressurizer#157]
**Describe the bug**
I'm having NullReferenceException after selecting profile and pressing OK button in Create Profile window:

**To Reproduce:**
1. Go to 'Select Profile and select a profile'
2. Click on 'OK button'
3. See error:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.Profile.Save(String path)
   at Depressurizer.DlgProfile.CreateProfile()
   at Depressurizer.DlgProfile.Apply()
   at Depressurizer.DlgProfile.cmdOk_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
**Expected behavior:**
profile imported successfully. 

**Desktop:**
OS: [Win 10]
Version [1903]
.NET Version [4.7]

**Additional context:**
this is a clean installation of 4.12.0 with appdata folder removed.

**Comment by mvegter** [comment]
Fixed in https://github.com/Depressurizer/Depressurizer/commit/1734772ae871ca1c9fb046361a612b670383260d, thanks for reporting!
