### ISSUE TITLE
[BUG] Issue trying to update game list for steam account

### ISSUE THREAD

**Issue by RainRunner54** [Depressurizer/Depressurizer#175]
I get the following fatal errors in quick succession while trying to select my steam profile on starting depressurizer:

**Error Message 1**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.GameList.IntegrateGameList(GetOwnedGamesObject doc, Boolean overwrite, SortedSet`1 ignore, Int32& newItems)
   at Depressurizer.CDlgUpdateProfile.Finish()
   at Depressurizer.Dialogs.CancelableDialog.CancelableDialog_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

**Error Message 2**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.GameList.IntegrateGameList(GetOwnedGamesObject doc, Boolean overwrite, SortedSet`1 ignore, Int32& newItems)
   at Depressurizer.CDlgUpdateProfile.Finish()
   at Depressurizer.Dialogs.CancelableDialog.CancelableDialog_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at Rallion.FatalError.HandleUnhandledException(Exception e)
   at Rallion.FatalError.Application_ThreadException(Object sender, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Error Message 3**'
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at Depressurizer.Dialogs.CancelableDialog.CheckClose()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

1. Go to C:\Users\XXX\Downloads\Depressurizer-v4.12.1
2. Click on Depressurizer.exe
3. Select my steam account under "Select User" on the "Create Profile" window.
4. Click "Ok"
5. Paste Steam Web API Key
6. Click "Save Key"
6. See Error 1
7. Click OK
8. See Error 2
9. Click OK
10. See Error 3

**Expected behavior**
Successful launch after collecting my game list from my steam account.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version v4.12.1
 -  .NET Version 
 - 2.0.50727.4927 Service Pack 2
 - 3.0.30729.4926 Service Pack 2
 - 3.5.30729.4926 Service Pack 1
 - 4.0.0.0
 - 4.8.03752

**Additional context**
I tried to install .NET Framework 4.6.2 but it wouldn't let me because I have a newer version.

**Comment by mvegter** [comment]
Hi @RainRunner54 , thanks for your report. Please check the [latest release](https://github.com/Depressurizer/Depressurizer/releases/latest) and see if this is still happening.
