### ISSUE TITLE
Fatal Error - IndexOutOfRangeException

### ISSUE THREAD

**Issue by JourneyOver** [Depressurizer/Depressurizer#48]
**Describe the bug**
After trying to "scrap unscrapped" for several hours, I have now run into a fatal error popup message with the below error message and stack traces.

`Index was outside the bounds of the array.`

```
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Depressurizer.Dialogs.ScrapeDialog.OnFinish()
   at Depressurizer.Dialogs.CancelableDialog.CancelableDialog_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

```
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Depressurizer.Dialogs.ScrapeDialog.OnFinish()
   at Depressurizer.Dialogs.CancelableDialog.CancelableDialog_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   at System.Windows.Forms.Application.ExitInternal()
   at System.Windows.Forms.Application.Exit(CancelEventArgs e)
   at Depressurizer.Dialogs.FatalErrorDialog.HandleUnhandledException(Exception e)
   at Depressurizer.Dialogs.FatalErrorDialog.Application_ThreadException(Object sender, ThreadExceptionEventArgs e)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at MaterialSkin.Controls.MaterialForm.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**
1. Go to 'database editor'
2. Uncheck 'show owned only'
3. Click on 'fetch list then update appinfo and then click on scrap unscrapped'
4. let it go for a few hours
5. See error

**Expected behavior**
For it to not throw this error, along with it scrapping all the unscrapped stuff.

**Screenshots**
![dhnioe1](https://user-images.githubusercontent.com/13910285/42254682-80f54b72-7f0d-11e8-8236-c83291ae7c28.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 Pro 
 - Version: 3.0.0

**Additional context**
There is a problem with scrapping in general it seems in the latest release.. Every couple hundred or so scraps it would just completely stop until I clicked the stop button and then started the "scrap unscrapped" back up again.

**Comment by mvegter** [comment]
@JourneyOver Have you experienced this issue using the latest version?

**Comment by JourneyOver** [comment]
I sadly don't have a computer at the moment since mine decided to break..so I can't really say yes or no atm.

**Comment by mvegter** [comment]
Closing this issue after a prolonged period of inactivity. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.

**Comment by JourneyOver** [comment]
Sorry about that, still don't have a computer so sadly never could test with any new releases in the past couple of months.. but will do whenever I get either a new computer or get mine back from repair shop.

**Comment by JourneyOver** [comment]
Can say that this bug seems to have either been fixed, or I just am not running into it anymore as well I'm not running into it anymore on the latest release since I'm back up and running with a computer again.
