### ISSUE TITLE
[BUG] DirectoryNotFoundException for Settings

### ISSUE THREAD

**Issue by jusuchin85** [Depressurizer/Depressurizer#53]
**Describe the bug**
Depressurizer does not load on a Windows 10 system with .NET Framework 4.7.2

**To Reproduce**

1. Steps to reproduce the behavior:
2. Extract downloaded Depressurizer 3.0.0
3. Double click on **Depressurizer.exe**
4. Check Task Manager and noticed that the program is listed there. After some time, the program disappears from the list

**Expected behaviour**
The program loads normally.

**Error Logs**
The following appears in the **Event Viewer**:
Check Event Log viewer, and got this messages:

```
Application: Depressurizer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at System.IO.Directory.CreateDirectory(System.String)
   at Depressurizer.Core.Helpers.Location+Folder.get_Logs()
   at Depressurizer.Core.Helpers.Location+File.get_Log()
   at Depressurizer.Core.Helpers.Logger..ctor()
   at Depressurizer.Core.Helpers.Logger.get_Instance()
   at Depressurizer.Core.Settings.Load(System.String)
   at Depressurizer.Program.Main(System.String[])
```
```
Faulting application name: Depressurizer.exe, version: 3.0.0.0, time stamp: 0x5b392a45
Faulting module name: KERNELBASE.dll, version: 10.0.17134.165, time stamp: 0xfa43f4b2
Exception code: 0xe0434352
Fault offset: 0x0010ddc2
Faulting process id: 0x40e0
Faulting application start time: 0x01d41c99feab2c7e
Faulting application path: C:\Users\Justin Alex\Downloads\Applications\Depressurizer-v3.0.0\Depressurizer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 64f9614c-0ddb-4c6f-ab7a-074a9ef5a7bd
Faulting package full name: 
Faulting package-relative application ID: 
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Pro 1803 (build no. 17134.165)

**Additional context**
I understand that .NET Framework 4.6.2 is required to use Depressurizer. However, the latest Windows 10 update has upgraded the framework to version 4.7.2. I can't seem to install the [4.6.2 version](https://www.microsoft.com/en-us/download/details.aspx?id=53344), as the latest version is already installed.

I also tried to install the [4.6.2 Developer Pack](https://www.microsoft.com/en-us/download/details.aspx?id=53321) but that didn't help either.

**Comment by mvegter** [comment]
This doesn't seem to be an issue related to your .NET Framework. Looking at the first log you provided it seems that during the creation of the Logs folder, in the Depresssurizer appdata folder, an error occurred.

To be honest I have no clue what this could be, going to dig further into it.

**Comment by mvegter** [comment]
@jusuchin85 Could you check if this still happens with the [latest release](https://github.com/mvegter/Depressurizer/releases).

**Comment by jusuchin85** [comment]
@mvegter , unfortunately, it is still occurring. I've got the same error messages in the Event Viewer:

```
Application: Depressurizer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at System.IO.Directory.CreateDirectory(System.String)
   at Depressurizer.Core.Helpers.Location+Folder.get_Logs()
   at Depressurizer.Core.Helpers.Location+File.get_Log()
   at Depressurizer.Core.Helpers.Logger..ctor()
   at Depressurizer.Core.Helpers.Logger.get_Instance()
   at Depressurizer.Core.Settings.Load(System.String)
   at Depressurizer.Program.Main(System.String[])
```

**Comment by mvegter** [comment]
@jusuchin85 I renamed the issue because it is not related to the Framework itself, it might have to do with permissions but I'm not sure.

**Comment by jusuchin85** [comment]
@mvegter I just reinstalled my Windows (for a refresh). When I attempted to run Depressurizer 3.1.0, it opens up nicely now.

Still not sure what went wrong earlier, but I guess we can close this off?
