### ISSUE TITLE
Error Updating From Local Files:  The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by C-O-S** [Depressurizer/Depressurizer#64]
When starting Version 3.1.0 I received this error every time:
![dep](https://user-images.githubusercontent.com/33273295/44913634-f7440900-acfb-11e8-85f4-ab4d709c5165.PNG)

I have removed  (WIN + R -> %appdata% -> Depressurizer) and allowed it to rebuild from scratch however the error persists.

Exception/Errors thrown in the log are as follows:

Opening App:
08/31/2018 08:54:45 Error   | Exception when performing local update.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()

...
Closing/saving profile:

08/31/2018 08:56:09 Error   | Error opening Steam config file: System.IO.FileNotFoundException: Could not find file 'D:\Games\Steam\userdata\ _removed_ \config\shortcuts.vdf'.
File name: 'D:\Games\Steam\userdata\ _removed_ \config\shortcuts.vdf'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Depressurizer.GameList.ExportSteamShortcuts(Int64 SteamId)

**Comment by C-O-S** [comment]
Confirming error persists in version 4.1.0.0:

> 11:55:51.110554 -  ERR: Exception when performing local update.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   at Depressurizer.FormMain.UpdateLibrary()

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
