### ISSUE TITLE
NRE crash when opening Browser

### ISSUE THREAD

**Issue by joebehymer** [Depressurizer/Depressurizer#87]
NullReferenceException crash when clicking the Browser checkbox, with or without game selected.

Running Depressurizer 4.2.0.0 on Win10, extracted from a zip file to my users directory.  Just upgraded from an old version (0.something).  I originally left the old files in the folder to avoid re-downloading all of the banners, but it seems this happens with a fresh install for me as well.  

Screenshot: https://imgur.com/a/tUCLAQJ

Stack trace:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.FixWebBrowserRegistry()
   at Depressurizer.FormMain.mchkBrowser_CheckedChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by menace97** [comment]
Depressurizer Fatal Error
![2018-12-07 07-07-41 pm](https://user-images.githubusercontent.com/9943387/49680636-174e3b80-fa54-11e8-9a89-1cfc3401f80c.png)

Happens every time any game is selected within Depressurizer, by selecting the **Browser checkbox** at the top of the screen to find the selected title on Steam website.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.FixWebBrowserRegistry()
   at Depressurizer.FormMain.mchkBrowser_CheckedChanged(Object sender, EventArgs e)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by joebehymer** [comment]
Hey @menace97 , if you want to fix this before somebody fixes the code, you can create the registry key yourself that the app is failing to create properly.  

Create a new DWORD value here:

> Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION

Name: Depressurizer.exe
Type: REG_DWORD
Value (Decimal): 11000

**Comment by mvegter** [comment]
Closing this due to inactivity, feel free to reopen if this still doesn't work.
