### ISSUE TITLE
NRE When Sorting All Games List & Then Clicking On Game

### ISSUE THREAD

**Issue by WandersenCS** [Depressurizer/Depressurizer#88]
Happens consistently on Win 10 64bit. Go to "All Games" tab, sort it by anything really (Ex: "User Score"), click on any game.

Running 4.3.0 version of the software.

Detailed Error Message:

System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__108_6(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.ListViewNativeItemCollection.get_Item(Int32 displayIndex)
   at System.Windows.Forms.ListView.ListViewItemCollection.get_Item(Int32 index)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by skelhammer** [comment]
Same issue is happening every time I open 4.3.0. 
Windows 10x64 1803. 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__108_6(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by mvegter** [comment]
Thanks for the feedback, going to look into it.

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
