### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by caedis21** [Depressurizer/Depressurizer#90]
**Describe the bug**
Error occurs as soon as Depressurizer is launched. 

**To Reproduce**
1. Launch Depressurizer

**Expected behavior**
Depressurizer gives a System.NullReferenceException error and crashes. 

**Error Log**
System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__108_6(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Desktop (please complete the following information):**
Windows 10 x64

**Comment by rtrman** [comment]
I also received the above error with the attached stack trace:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Depressurizer.FormMain.<>c.<InitializeLstGames>b__108_6(Object g)
   at BrightIdeasSoftware.OLVColumn.GetValue(Object rowObject)
   at BrightIdeasSoftware.ObjectListView.MakeSubItem(Object rowObject, OLVColumn column)
   at BrightIdeasSoftware.ObjectListView.FillInValues(OLVListItem lvi, Object rowObject)
   at BrightIdeasSoftware.VirtualObjectListView.MakeListViewItem(Int32 itemIndex)
   at BrightIdeasSoftware.VirtualObjectListView.HandleRetrieveVirtualItem(Object sender, RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.OnRetrieveVirtualItem(RetrieveVirtualItemEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

This occured after launching depressurizer, selecting my install folder, selecting my account, and launching the main app.
I now receive the above error on launching the app.
From reading the stack trace, I wonder if it is related to a few emulator games I linked into my library using [ICE for Steam](https://steamcommunity.com/linkfilter/?url=http://scottrice.github.io/Ice/)

**Comment by mvegter** [comment]
@rtrman Thanks for your information, it helped a lot. The problem is caused by a wrong check in the code. Expect a release soon.

**Comment by mvegter** [comment]
Closing this issue. If this is still present in the latest release, please feel free to create a new issue with up-to-date information.
